version: '3.8'

services:
  web:
    build: .
    image: my-rails-app:production
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: <%= ENV['POSTGRES_USER'] %>
      POSTGRES_PASSWORD: <%= ENV['POSTGRES_PASSWORD'] %>
      POSTGRES_DB: <%= ENV['POSTGRES_DB'] %>
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    restart: always

volumes:
  pgdata:
