version: '3.8'

services:
  db:
    image: postgres:15
    container_name: effective-octo-robot-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: effective-octo-robot
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build:
      context: .
    container_name: effective-octo-robot-web
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:password@db:5432/effective-octo-robot
      RAILS_MASTER_KEY: e7b214f3efded128e161bb6a79e71291
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]

volumes:
  postgres-data:
